export const CREATE_UNKNOWN_TOPIC = "CREATE_UNKNOWN_TOPIC";
export const RETRIEVE_UNKNOWN_TOPICS = "RETRIEVE_UNKNOWN_TOPICS";
export const UPDATE_UNKNOWN_TOPIC = "UPDATE_UNKNOWN_TOPIC";
export const DELETE_UNKNOWN_TOPIC = "DELETE_UNKNOWN_TOPIC";
export const DELETE_ALL_UNKNOWN_TOPICS = "DELETE_ALL_UNKNOWN_TOPICS";